### ISSUE TITLE
git clone checkout failure

### ISSUE THREAD

**Issue by karlhiramoto** [dparrish/libcli#1]
I think somehow you messed up your repository..

git clone git://github.com/dparrish/libcli.git
Initialized empty Git repository in /home/karl/Work/libcli/.git/
remote: Counting objects: 494, done.
remote: Compressing objects: 100% (405/405), done.
remote: Total 494 (delta 51), reused 435 (delta 8)
Receiving objects: 100% (494/494), 576.42 KiB | 173 KiB/s, done.
Resolving deltas: 100% (51/51), done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.

**Comment by dparrish** [comment]
Hrm that's an odd one, I'm not sure why but I'll look into it.

For now, after you've done a clone, you can do:
cd libcli
git checkout origin/stable
git checkout -b stable

**Comment by dparrish** [comment]
This should be fixed now. FYI it required setting the default branch to version-2.0 and then back to stable.
