### ISSUE TITLE
command completion does not work on filters

### ISSUE THREAD

**Issue by FransM** [dparrish/libcli#35]
command completion for filters does not work as expected

E.g. build clitest, run it, telnet to it then do
show counters |
followed by tab -> no completion, no alternatives (also not after pressing tab a second time
show counters | g
followed by tab -> as above
show counters |
followed by ? -> gives a list of all options (as expected)
show counters | g
followed by ? -> again gist a list of all alternatives. I had expected only filters starting with g (just like happens with commands)

**Comment by RobSanders** [comment]
As mentioned above, issue appears to be fixed
