### ISSUE TITLE
filter abbreviations gives unexpected results

### ISSUE THREAD

**Issue by FransM** [dparrish/libcli#36]
If as a a filter I give "| e" egrep is chosen although the e also could match exclude
I had expected an error or autocompletion hint.
I suspect I got egrep because it is alphabetically first.

Example:

router> show counters | e call 
called cmd_test with "show counters"

router> show counters | eg call
called cmd_test with "show counters"

router> show counters | ex call
0 arguments:

I suspect something similar will happen with "b"  as it can match begin and between

**Comment by RobSanders** [comment]
Work done in V1.10.0 fixed this so filters are treated 'like' commands.  If you don't give enough letters to unambiguously identify the command it will report 'invalid command' with the letters typed.
