### ISSUE TITLE
Tag 1.9.5 Release

### ISSUE THREAD

**Issue by ekarulf** [dparrish/libcli#4]
Hi David,

Would you mind tagging the 1.9.5 release?

I'm submitting a patch for the FreeBSD port and I'd prefer to use the Github download URL.

Out of kindness to the portmaintainers, would you mind using the 'v1.9.5' format for tagging?

Thanks!

-Erik

**Comment by dparrish** [comment]
Done. v1.9.5 is tagged and signed.
