### ISSUE TITLE
Please provide real distfiles

### ISSUE THREAD

**Issue by bapt** [dparrish/libcli#5]
Hi,

I am maintaining a freebsd port for libcli. but in order to be able to provide it we need a real distfile.

github guys also think that the tags aren't clean distfiles: 
http://support.github.com/discussions/repos/4017-tags-and-distfile-generation-issues

The main problem for us is the http redirection. With true distfiles we can access a directly link with no redirection: cloud.github.com with tags we can't plus the checksum changes each time the tarball associated to the tag is regenerated by github.

Thanks
Bapt

**Comment by dparrish** [comment]
I've built a release file for 1.9.5 at https://github.com/downloads/dparrish/libcli/libcli-1.9.5.tar.gz

**Comment by bapt** [comment]
Thanks, freebsd ports updated :)
