### ISSUE TITLE
Build failure on darwin: `error: implicit declaration of function 'strchrnul' is invalid in C99`

### ISSUE THREAD

**Issue by trofi** [dparrish/libcli#78]
Noticed by @bobby285271 in https://github.com/NixOS/nixpkgs/pull/147749 when we attempted to update `libcli` in NixOS.

Build fails on Darwin libc as:

```
libcli.c:2521:41: error: implicit declaration of function 'strchrnul' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  if (help && !(c->help = strndup(help, strchrnul(help, '\v') - help))) {
```

Full build log: https://logs.nix.ci/?key=nixos/nixpkgs.147749&attempt_id=54ba70b3-6044-4233-ab14-a2ecea5c68e8

Looks like `strchrnul()` needs to be avoided on non-GNU systems.

**Comment by RobSanders** [comment]
Apologies for the very overdue response.  Have recoded to not call strchrnul in that routine.  Issue fixed in the 1.10.8 release.
